{
 "title": "Car Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Moving Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TCICOnStarGPSPosition",
     "select": [
      [
       { "params": [ "GPSLatitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "GPSLongitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "alias": "Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Vehicle_Speed_and_Distance",
     "select": [
      [
       { "params": [ "speed_average_driven" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driver Inputs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Steering Wheel Angle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Steering_Wheel_Angle",
     "select": [
      [
       { "params": [ "steering_wheel_angle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Throttle Pedal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Engine_General_Status_1",
     "select": [
      [
       { "params": [ "accelerator_actual_position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "%Brake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Engine_General_Status_1a",
     "select": [
      [
       { "params": [ "platform_brake_position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Boost %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Boost",
     "measurement": "PPEI_Engine_General_Status_2",
     "select": [
      [
       { "params": [ "boost_pressure_indication" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commanded AFR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "PPEI_Fuel_Sytem_Request_2",
     "select": [
      [
       { "params": [ "Commanded_Air_Fuel_Ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fuel Tank",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PPEI_Engine_General_Status_5",
     "select": [
      [
       { "params": [ "fuel_level_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gear",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PPEI_Transmission_General_Status_2",
     "select": [
      [
       { "params": [ "transmission_commanded_gear" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine RPM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "alias": "Engine RPM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Engine_General_Status_1",
     "select": [
      [
       { "params": [ "engine_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oil Pressure",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PPEI_Engine_General_Status_5",
     "select": [
      [
       { "params": [ "engine_oil_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PPEI_Engine_General_Status_1",
     "select": [
      [
       { "params": [ "engine_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "KPH" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PPEI_Vehicle_Speed_and_Distance",
     "select": [
      [
       { "params": [ "speed_average_driven" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lateral Acceleration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "alias": "Lateral Acceleration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Chassis_General_Status_1",
     "select": [
      [
       {
        "params": [
         "vehicle_stability_lateral_acceleration"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Coolant Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Engine_General_Status_4",
     "select": [
      [
       { "params": [ "engine_coolant_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Intake Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Engine_General_Status_4",
     "select": [
      [
       { "params": [ "engine_intake_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Oil Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Engine_General_Status_5",
     "select": [
      [
       { "params": [ "engine_oil_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Ambient Air Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Engine_General_Status_4",
     "select": [
      [
       {
        "params": [
         "outside_air_temperature_estimate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Trans Oil Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "PPEI_Transmission_General_Status_3",
     "select": [
      [
       { "params": [ "trans_oil_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}